version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    command: yarn start
    environment:
      - MONGODB_URL=mongodb://u4540:f4rdaS4rma@27017/mail-listener
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
#    volumes:
#      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: u4540
      MONGO_INITDB_ROOT_PASSWORD: f4rdaS4rma
    volumes:
      - db_data:/data/db
    networks:
      - node-network

volumes:
  dbdatav6:

networks:
  node-network:
    driver: bridge
