version: '3'

services:
#  node-app:
#    build: .
#    image: node-app
#    command: yarn start
#    environment:
#      - MONGODB_URL=mongodb://mongodb:27017/mail-listener
#    ports:
#      - '3000:3000'
#    depends_on:
#      - mongodb
#    volumes:
#      - .:/usr/src/node-app
#    networks:
#      - node-network

  mongodb:
    image: mongo:6.0.13-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdatav6:/data/db
    networks:
      - node-network

volumes:
  dbdatav6:

networks:
  node-network:
    driver: bridge
